path: 'C:\Users\mleroux\Documents\projet_fin_dannee\training_reconaissance\training_reconaissance\training_reconaissance\data'
train: 'images/train'
val: 'images/train'
 
#classes:
nc: 1
names: ['person']